### PR TITLE
Add certificate JSON schema.

### PR DESCRIPTION
**Pull request by Natim**
This eventually raises a 500 on kinto.dev but the idea is there.

### CODE REVIEW

**Comment by Natim** [comment]
@n1k0 do you know if the schema needs to be updated here?

**Comment by n1k0** [comment]
I have no idea. It reflects the data schema from current the blocklist.xml file so I suspect it's fine, but no 100% guarantee. Maybe @jvillalobos has an idea, or has clue who we should ask about that?

**Comment by jvillalobos** [comment]
The issuer and serial is all we need in the blocklist. We should also store a bug number for internal reference, but it doesn't need to be downloaded by the client.

**Comment by magopian** [comment]
Very good starting point. We now need to improve on this PR to also include the schemas for the other collections.

Maybe we could use something equivalent to the PR #9 to download/update the schema from https://github.com/mozilla-services/amo-blocklist-ui/blob/master/amo-blocklist.json, and then in the `__main__` check that the collection already exist, or create them using the schemas from this json?

**Comment by Natim** [comment]
> Maybe we could use something equivalent to the PR #9 to download/update the schema from https://github.com/mozilla-services/amo-blocklist-ui/blob/master/amo-blocklist.json, and then in the __main__ check that the collection already exist, or create them using the schemas from this json?

Yes let's do that.

**Comment by Natim** [comment]
Superseeded by https://github.com/mozilla-services/xml2kinto/pull/34

**Pull request closed without merging**
